name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build-and-deploy:
    env:
      NEXT_TELEMETRY_DISABLED: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install
      - run: npm run build
      - run: npm run export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out
